
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load -u -v -x -t elf"

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "picotool load -u -v -x -t elf"

[build]
# target = "thumbv8m.main-none-eabihf"
target = "riscv32imac-unknown-none-elf"

[env]
DEFMT_LOG = "debug"
